name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
          client_id: cf4141aa-04ce-486e-b0fc-7a3451f64778
          client_secret: vtE8Q~3efd4Dca3xv4VUWueogFjzpS9iCK3fmc0k
          subscription_id: 044401d3-520c-4903-b46c-4d4cffe66a56
          tenant_id: 763ec90f-0953-4611-b0f4-b840899e0923

      - name: AZ Account Show Details
        run: az account show
