name: Deploy to Azure
on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
jobs:
  my_job:
    name: Running on Virtual Machine
    runs-on:
          - self-hosted
          - Linux
          - X64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Show Runner Information
        run: |
          echo "Hostname:"
          hostname
          echo "Current Directory:"
          pwd

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Check Azure Account Details
        run: |
          echo "===== Azure Account Details ====="
          az account show --output table
